### PR TITLE
Build the published bundle in CI and run it end to end

### PR DESCRIPTION
**Pull request by matmannion**
Dependency bumps have needed a manual check before merging, because CI does not prove very much: it only type-checks. It never builds the bundle that actually gets published, and nothing ever runs the tool, so a bump can go green while breaking it at runtime.

The aim here is a Build job green enough to judge a bump on, without first running the tool against real Slack and GitLab. Merging stays manual.

**Build now also bundles and runs the CLI end to end.** `scripts/smoke-test.mjs` executes `dist/roulette.js` against stub Slack and GitLab servers on loopback — no credentials, no network — and asserts the merge request author is excluded, holiday reviewers are filtered out, one maintainer plus one other developer are named, and that the create / leave-alone / replace-on-checkbox branches for the note all behave.

To confirm that is a real gate and not decoration, breaking author-exclusion in a way that still type-checks leaves `npm run tsc` passing and fails the smoke test on exactly the two affected assertions.

**It immediately found a live bug, which the first commit fixes.** `https-proxy-agent` 9 is ESM-only and the published bundle is CommonJS, so requiring it throws `ERR_REQUIRE_ESM` before any of our code runs. Version 1.0.7 as published on npm cannot start at all on the 20.11.0 that `.node-version` pins — verified by running the packed tarball on that exact runtime. It only appears to work because newer Node supports `require(esm)`. Bundling it inline lets esbuild emit CommonJS, and the proxy path is confirmed working on both 20.11.0 and current Node from a clean production install.

Also bumps `actions/checkout` and `actions/setup-node` off v3, which was being forced onto Node 24 with deprecation warnings, and takes the Node version from `.node-version` instead of repeating it in a matrix.

### Worth knowing

- `@types/node` reaches this project only as a transitive dependency of `@slack/web-api`. That is why the TypeScript 7 bump fails with eleven "Cannot find name 'process'" errors. It should probably become a direct devDependency.
- Not fixed here: `createOrUpdateNote` never returns its `fetch`, so the comment POST is fire-and-forget. If GitLab rejects it the process still exits 0, reporting success having posted nothing.

### CODE REVIEW

**Review by henricook — APPROVED** [review]

**Comment by henricook** [comment]
Great addition, thanks!
